# Generated by Django 3.2.9 on 2022-04-17 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import school.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schools_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schools_Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_image', models.ImageField(upload_to=school.models.filepath)),
            ],
        ),
        migrations.CreateModel(
            name='Student_admission_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to=school.models.filepath)),
                ('school_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schools_name')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student_admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('stud_image', models.ImageField(upload_to=school.models.filepath)),
                ('student_class', models.CharField(max_length=50)),
                ('School_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schools_name')),
                ('stud_admis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_image', models.ImageField(upload_to=school.models.filepath)),
                ('pay', models.BooleanField(default=False)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schools_name')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school_class')),
            ],
        ),
        migrations.CreateModel(
            name='School_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_description', models.TextField(null=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school_Profiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schools_profiles')),
            ],
        ),
        migrations.CreateModel(
            name='School_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=100)),
                ('school_image', models.ImageField(upload_to=school.models.filepath)),
                ('schools_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schools_profiles')),
            ],
        ),
        migrations.AddField(
            model_name='school_class',
            name='school_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schools_name'),
        ),
        migrations.CreateModel(
            name='Refuse_Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schools_name')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Accepted_Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schools_name')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
